// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cybervasyan/pdididy-project/inventory/internal/repository/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, partUUID
func (_m *MockRepository) Get(ctx context.Context, partUUID uuid.UUID) (model.Part, error) {
	ret := _m.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return rf(ctx, partUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = rf(ctx, partUUID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx interface{}, partUUID interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, partUUID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, partUUID uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(_a0 model.Part, _a1 error) *MockRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Part, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req
func (_m *MockRepository) List(ctx context.Context, req model.PartsFilter) ([]model.Part, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.PartsFilter
func (_e *MockRepository_Expecter) List(ctx interface{}, req interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, req model.PartsFilter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []model.Part, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, model.PartsFilter) ([]model.Part, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
