// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cybervasyan/pdididy-project/payment/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPayment is an autogenerated mock type for the Payment type
type MockPayment struct {
	mock.Mock
}

type MockPayment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPayment) EXPECT() *MockPayment_Expecter {
	return &MockPayment_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, userUUID, paymentMethod
func (_m *MockPayment) PayOrder(ctx context.Context, orderUUID uuid.UUID, userUUID uuid.UUID, paymentMethod model.PaymentMethod) (uuid.UUID, error) {
	ret := _m.Called(ctx, orderUUID, userUUID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)); ok {
		return rf(ctx, orderUUID, userUUID, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) uuid.UUID); ok {
		r0 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) error); ok {
		r1 = rf(ctx, orderUUID, userUUID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPayment_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPayment_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - userUUID uuid.UUID
//   - paymentMethod model.PaymentMethod
func (_e *MockPayment_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, userUUID interface{}, paymentMethod interface{}) *MockPayment_PayOrder_Call {
	return &MockPayment_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, userUUID, paymentMethod)}
}

func (_c *MockPayment_PayOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, userUUID uuid.UUID, paymentMethod model.PaymentMethod)) *MockPayment_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.PaymentMethod))
	})
	return _c
}

func (_c *MockPayment_PayOrder_Call) Return(_a0 uuid.UUID, _a1 error) *MockPayment_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPayment_PayOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.PaymentMethod) (uuid.UUID, error)) *MockPayment_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPayment creates a new instance of MockPayment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPayment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPayment {
	mock := &MockPayment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
