name: Run Unit Tests

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v6

      - name: 🛠 Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ inputs.go-version }}
          cache: false # отключаем кэш go.sum в корне

      - name: 📌 Install Task
        run: go install github.com/go-task/task/v3/cmd/task@v3.52.0

      - name: 🧪 Run unit tests via Taskfile
        env:
          MODULES: ${{ inputs.modules }}
        run: task test
